org: diaslucas
app: coffee-shop
service: coffee-shop-serverless


plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  stage: ${opt:stage, 'dev'}
  tableName: OrdersTable
  serverless-offline:
    useChildProcesses: true 
  serverless-dynamodb:
    start:
      port: 8000
      docker: false
    
provider: ${file(./configurations/provider.yml)}

functions: ${file(./configurations/functions.yml)}

resources: ${file(./configurations/resources.yml)}
