org: diaslucas
app: coffee-shop
service: coffee-shop-serverless

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-dynamodb
  - serverless-offline

custom: ${file(./configurations/custom.yml)}

provider: ${file(./configurations/provider.yml)}

functions: ${file(./configurations/functions.yml)}

resources: ${file(./configurations/resources.yml)}

