org: lucasdias
app: coffee-shop
service: coffee-shop-serverless

plugins:
  - serverless-dynamodb

provider: ${file(./configurations/provider.yml)}

functions: ${file(./configurations/functions.yml)}

resources: ${file(./configurations/resources.yml)}
