org: lucasdias
app: coffe-shop
service: coffe-shop-serverless



provider: ${file(./configurations/provider.yml)}

functions: ${file(./configurations/functions.yml)}

resources: ${file(./configurations/resources.yml)}
