dynamodbEndpoint:
    dev: http://localhost:8000
    prod: null
stages:
  - prod
  - dev
tableName: OrdersTable
dynamodb:
  start:
    port: 8000
    inMemory: true
    migrate: true
  stages:
    - dev
serverless-offline:
  useChildProcesses: true 
serverless-dynamodb:
  start:
    port: 8000
    docker: false
prune:
    automatic: true
    number: 3
webpack:
  webpackConfig: webpack.config.cjs  
