name: Serverless Coffee-Shop CI/CD - DEV

on:
    pull_request:
        branches:
        - master

              
jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
            cache: 'yarn'
  
        - name: Install dependencies
          run: yarn ci
  
        - name: Run tests
          run: yarn test
  
    deploy-dev:
      name: deploy-dev
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
            cache: 'yarn'
  
        - name: Install dependencies
          run: yarn ci
  
        - name: Install Serverless Framework
          run: yarn global add serverless
  
        - name: Deploy to dev
          run: serverless offline start --stage dev
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}